---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app1
  namespace: jaeger
  labels:
    app: fastapi-app1
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: fastapi-app1 # it is a crd of DediServer. Pod has this label 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app1
  namespace: jaeger
  labels:
    app: fastapi-app1
spec:
  revisionHistoryLimit: 0 #NOTE: argocd
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app1
  template:
    metadata:
      labels:
        app: fastapi-app1
    spec:
      containers:
      - name: fastapi-app1
        image: rival0605/jaeger:fastapi-app1
        imagePullPolicy: Always
        command: ["python", "main.py"]
        # command: ["/bin/sh", "-c", "sleep inf"]
        args:
        env:
        - name: JAEGER_SERVICE_NAME
          value: fastapi-app1
        - name: JAEGER_AGENT_HOST
          value: simplest-agent  # simplest-agent # 사이드카 패턴이라면 localhost로 하고 agent를 추가한다. 
        - name: JAEGER_AGENT_PORT
          value: "6831"

# https://medium.com/@masroor.hasan/tracing-infrastructure-with-jaeger-on-kubernetes-6800132a677
